import Head from "next/head";
import Image from "next/image";
import Logo from "../public/logo.png";
import About from "@/components/About";
import Navbar from "@/components/Navbar";
import React, { useRef, useState } from "react";
import TheTeam from "@/components/TheTeam";
import Hero from "@/components/Hero";
import ContactMeBlock from "@/components/ContactMe";
import Snackbar from "@/components/SnackbarMessage";

export default function Home() {
  const aboutRef = useRef(null);
  const teamRef = useRef(null);
  const contactRef = useRef(null);

  // Add Snackbar state
  const [snackbarVisible, setSnackbarVisible] = useState(false);
  const [snackbarMessage, setSnackbarMessage] = useState("");

  // Function to display the snackbar with a custom message
  const showSnackbar = (message) => {
    setSnackbarMessage(message);
    setSnackbarVisible(true);
    setTimeout(() => setSnackbarVisible(false), 5000);
  };

  // Function to handle form submission
  const handleFormSubmit = () => {
    showSnackbar("We will be in contact shortly");
  };

  return (
    <>
      <Head>
        <title>Next Rewarders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar aboutRef={aboutRef} teamRef={teamRef} contactRef={contactRef} />
      <main>
        <Hero />
        <TheTeam ref={teamRef} />
        <About ref={aboutRef} />
        <ContactMeBlock ref={contactRef} onSubmit={handleFormSubmit} />
      </main>
      {snackbarVisible && (
        <Snackbar
          message={snackbarMessage}
          onClose={() => setSnackbarVisible(false)}
        />
      )}
    </>
  );
}
