import Head from "next/head";
import { Inter } from "@next/font/google";
import Link from "next/link";
import Image from "next/image";
import Logo from "../public/logo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Rewarders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-color-2 min-h-screen flex flex-col items-center justify-center">
        <div className="text-center">
          <p className="font-normal">Welcome to the</p>
          <h1 className="text-3xl font-bold mb-4 text-main">ONLY</h1>
        </div>
        <Image src={Logo} className="mt-[-25px] w-1/2 sm:w-1/4" />
        <div className="text-center">
          <h1 className="text-3xl font-bold mb-4 text-main">App</h1>
          <p className="font-normal mb-[35px] mt-[-10px]">You will ever need</p>
        </div>
        <Link
          href="../login_register"
          className="bg-main hover:bg-secondary text-color-2 px-4 py-2 rounded"
        >
          Login || Register
        </Link>
      </main>
    </>
  );
}
